package handler

import (
	"encoding/json"
	"net/http"
	"wxcloudrun-golang/db"
	"wxcloudrun-golang/db/model"
	"wxcloudrun-golang/util"
)

type RecipeDTO struct {
	ID         int64    `json:"id"`
	FamilyID   int64    `json:"familyId"`
	Name       string   `json:"name"`
	Images     []string `json:"images"`
	Content    string   `json:"content"`
	SortOrder  int64    `json:"sortOrder"`
	CreateTime int64    `json:"createTime"`
	UpdateTime int64    `json:"updateTime"`
}

func convertRecipeToDTO(r *model.Recipe) *RecipeDTO {
	var images []string
	if r.Images != "" {
		_ = json.Unmarshal([]byte(r.Images), &images)
	}
	if images == nil {
		images = []string{}
	}
	return &RecipeDTO{
		ID:         r.ID,
		FamilyID:   r.FamilyID,
		Name:       r.Name,
		Images:     images,
		Content:    r.Content,
		SortOrder:  r.SortOrder,
		CreateTime: r.CreateTime.UnixMilli(),
		UpdateTime: r.UpdateTime.UnixMilli(),
	}
}

type AddRecipeRequest struct {
	Name    string   `json:"name"`
	Images  []string `json:"images"`
	Content string   `json:"content"`
}

func AddRecipe(w http.ResponseWriter, r *http.Request) {
	openId, err := util.GetOpenIdFromHeader(r)
	if err != nil {
		util.ReturnErrorJSON(w, "未登录", err)
		return
	}

	var req AddRecipeRequest
	if err := util.BindJson(r, &req); err != nil {
		util.ReturnErrorJSON(w, "参数错误", err)
		return
	}

	var user model.UserInfoDBModel
	if err := db.Get().Where("openId = ?", openId).First(&user).Error; err != nil {
		util.ReturnErrorJSON(w, "用户不存在", err)
		return
	}

	if user.FamilyID == 0 {
		util.ReturnErrorJSON(w, "请先加入家庭", nil)
		return
	}

	if user.Role != "admin" {
		util.ReturnErrorJSON(w, "只有家长可以创建食谱", nil)
		return
	}

	imagesJson, _ := json.Marshal(req.Images)
	recipe := model.Recipe{
		FamilyID: user.FamilyID,
		Name:     req.Name,
		Images:   string(imagesJson),
		Content:  req.Content,
		// SortOrder will be 0 initially, or we can set it to ID later?
		// db.ts sets sortOrder = now. Let's set it to current timestamp in milli for simplicity
	}
	// Set SortOrder manually if we want it to be like timestamp
	// But SortOrder is int64.
	// Let's just let it be 0 or handle it. db.ts used Date.now().
	// We can't easily set it to ID before insert.
	// Let's create first, then update SortOrder to ID (or timestamp).
	// Actually, timestamp is better for "newer on top" if we use sort desc.

	// Let's use CreateTime logic. But SortOrder is explicit.
	// I'll just use 0 and let the frontend/logic handle it, or set it to a large number.
	// db.ts: sortOrder: now.

	// I'll set SortOrder after creation or just use 0?
	// Let's use time.Now().UnixMilli()

	// Wait, CreateTime is generated by DB.
	// I can just set SortOrder.
	// recipe.SortOrder = time.Now().UnixMilli() // Need time import.
	// Or I can just leave it 0. But reorder logic depends on it.
	// I will use ID as default sort order if I could, but I can't.
	// I'll just skip setting it here and let it be 0.
	// Wait, if it is 0, all new recipes are 0.
	// I should set it.

	if err := db.Get().Create(&recipe).Error; err != nil {
		util.ReturnErrorJSON(w, "创建食谱失败", err)
		return
	}

	// Update sort order to match ID or something unique if needed, or just use timestamp
	db.Get().Model(&recipe).Update("sort_order", recipe.CreateTime.UnixMilli())
	recipe.SortOrder = recipe.CreateTime.UnixMilli()

	util.ReturnSuccessJSON(w, convertRecipeToDTO(&recipe))
}

func GetRecipes(w http.ResponseWriter, r *http.Request) {
	openId, err := util.GetOpenIdFromHeader(r)
	if err != nil {
		util.ReturnErrorJSON(w, "未登录", err)
		return
	}

	var user model.UserInfoDBModel
	if err := db.Get().Where("openId = ?", openId).First(&user).Error; err != nil {
		util.ReturnErrorJSON(w, "用户不存在", err)
		return
	}

	if user.FamilyID == 0 {
		util.ReturnSuccessJSON(w, []RecipeDTO{})
		return
	}

	var recipes []model.Recipe
	if err := db.Get().Where("family_id = ?", user.FamilyID).Order("sort_order desc").Find(&recipes).Error; err != nil {
		util.ReturnErrorJSON(w, "查询失败", err)
		return
	}

	var dtos []RecipeDTO
	for _, recipe := range recipes {
		dtos = append(dtos, *convertRecipeToDTO(&recipe))
	}

	util.ReturnSuccessJSON(w, dtos)
}

type UpdateRecipeRequest struct {
	ID      int64    `json:"id"`
	Name    string   `json:"name"`
	Images  []string `json:"images"`
	Content string   `json:"content"`
}

func UpdateRecipe(w http.ResponseWriter, r *http.Request) {
	openId, err := util.GetOpenIdFromHeader(r)
	if err != nil {
		util.ReturnErrorJSON(w, "未登录", err)
		return
	}

	var req UpdateRecipeRequest
	if err := util.BindJson(r, &req); err != nil {
		util.ReturnErrorJSON(w, "参数错误", err)
		return
	}

	var user model.UserInfoDBModel
	if err := db.Get().Where("openId = ?", openId).First(&user).Error; err != nil {
		util.ReturnErrorJSON(w, "用户不存在", err)
		return
	}

	if user.Role != "admin" {
		util.ReturnErrorJSON(w, "无权操作", nil)
		return
	}

	var recipe model.Recipe
	if err := db.Get().First(&recipe, req.ID).Error; err != nil {
		util.ReturnErrorJSON(w, "食谱不存在", err)
		return
	}

	if recipe.FamilyID != user.FamilyID {
		util.ReturnErrorJSON(w, "无权操作", nil)
		return
	}

	imagesJson, _ := json.Marshal(req.Images)
	recipe.Name = req.Name
	recipe.Images = string(imagesJson)
	recipe.Content = req.Content

	if err := db.Get().Save(&recipe).Error; err != nil {
		util.ReturnErrorJSON(w, "更新失败", err)
		return
	}

	util.ReturnSuccessJSON(w, convertRecipeToDTO(&recipe))
}

func DeleteRecipe(w http.ResponseWriter, r *http.Request) {
	openId, err := util.GetOpenIdFromHeader(r)
	if err != nil {
		util.ReturnErrorJSON(w, "未登录", err)
		return
	}

	idStr := r.URL.Query().Get("id")
	if idStr == "" {
		util.ReturnErrorJSON(w, "参数错误", nil)
		return
	}

	var user model.UserInfoDBModel
	if err := db.Get().Where("openId = ?", openId).First(&user).Error; err != nil {
		util.ReturnErrorJSON(w, "用户不存在", err)
		return
	}

	if user.Role != "admin" {
		util.ReturnErrorJSON(w, "无权操作", nil)
		return
	}

	var recipe model.Recipe
	if err := db.Get().Where("id = ?", idStr).First(&recipe).Error; err != nil {
		util.ReturnErrorJSON(w, "食谱不存在", err)
		return
	}

	if recipe.FamilyID != user.FamilyID {
		util.ReturnErrorJSON(w, "无权操作", nil)
		return
	}

	if err := db.Get().Delete(&recipe).Error; err != nil {
		util.ReturnErrorJSON(w, "删除失败", err)
		return
	}

	util.ReturnSuccessJSON(w, "删除成功")
}

type ReorderRecipeRequest struct {
	ID        int64  `json:"id"`
	Direction string `json:"direction"` // up, down
}

func ReorderRecipe(w http.ResponseWriter, r *http.Request) {
	openId, err := util.GetOpenIdFromHeader(r)
	if err != nil {
		util.ReturnErrorJSON(w, "未登录", err)
		return
	}

	var req ReorderRecipeRequest
	if err := util.BindJson(r, &req); err != nil {
		util.ReturnErrorJSON(w, "参数错误", err)
		return
	}

	var user model.UserInfoDBModel
	if err := db.Get().Where("openId = ?", openId).First(&user).Error; err != nil {
		util.ReturnErrorJSON(w, "用户不存在", err)
		return
	}

	if user.Role != "admin" {
		util.ReturnErrorJSON(w, "无权操作", nil)
		return
	}

	var current model.Recipe
	if err := db.Get().First(&current, req.ID).Error; err != nil {
		util.ReturnErrorJSON(w, "食谱不存在", err)
		return
	}

	if current.FamilyID != user.FamilyID {
		util.ReturnErrorJSON(w, "无权操作", nil)
		return
	}

	var target model.Recipe
	var errTarget error

	// sort_order desc.
	// Up means moving to earlier position (visual top), so HIGHER sort_order.
	// Down means moving to later position (visual bottom), so LOWER sort_order.
	if req.Direction == "up" {
		// Find the one with smallest SortOrder that is > current.SortOrder
		errTarget = db.Get().Where("family_id = ? AND sort_order > ?", user.FamilyID, current.SortOrder).Order("sort_order asc").First(&target).Error
	} else {
		// Find the one with largest SortOrder that is < current.SortOrder
		errTarget = db.Get().Where("family_id = ? AND sort_order < ?", user.FamilyID, current.SortOrder).Order("sort_order desc").First(&target).Error
	}

	if errTarget != nil {
		// No target found, meaning already at top or bottom
		util.ReturnSuccessJSON(w, "No change")
		return
	}

	// Swap
	tempOrder := current.SortOrder
	current.SortOrder = target.SortOrder
	target.SortOrder = tempOrder

	tx := db.Get().Begin()
	if err := tx.Save(&current).Error; err != nil {
		tx.Rollback()
		util.ReturnErrorJSON(w, "更新失败", err)
		return
	}
	if err := tx.Save(&target).Error; err != nil {
		tx.Rollback()
		util.ReturnErrorJSON(w, "更新失败", err)
		return
	}
	tx.Commit()

	util.ReturnSuccessJSON(w, "排序完成")
}

type BatchUpdateRecipesRequest struct {
	Recipes []struct {
		ID        int64 `json:"id"`
		SortOrder int64 `json:"sortOrder"`
	} `json:"recipes"`
}

func BatchUpdateRecipes(w http.ResponseWriter, r *http.Request) {
	openId, err := util.GetOpenIdFromHeader(r)
	if err != nil {
		util.ReturnErrorJSON(w, "未登录", err)
		return
	}

	var req BatchUpdateRecipesRequest
	if err := util.BindJson(r, &req); err != nil {
		util.ReturnErrorJSON(w, "参数错误", err)
		return
	}

	var user model.UserInfoDBModel
	if err := db.Get().Where("openId = ?", openId).First(&user).Error; err != nil {
		util.ReturnErrorJSON(w, "用户不存在", err)
		return
	}

	if user.Role != "admin" {
		util.ReturnErrorJSON(w, "无权操作", nil)
		return
	}

	tx := db.Get().Begin()
	for _, item := range req.Recipes {
		// Only update sort_order and verify family_id
		result := tx.Model(&model.Recipe{}).
			Where("id = ? AND family_id = ?", item.ID, user.FamilyID).
			Update("sort_order", item.SortOrder)

		if result.Error != nil {
			tx.Rollback()
			util.ReturnErrorJSON(w, "更新失败", result.Error)
			return
		}
	}

	if err := tx.Commit().Error; err != nil {
		util.ReturnErrorJSON(w, "事务提交失败", err)
		return
	}

	util.ReturnSuccessJSON(w, "批量更新成功")
}

func GetRecipe(w http.ResponseWriter, r *http.Request) {
	openId, err := util.GetOpenIdFromHeader(r)
	if err != nil {
		util.ReturnErrorJSON(w, "未登录", err)
		return
	}

	idStr := r.URL.Query().Get("id")
	if idStr == "" {
		util.ReturnErrorJSON(w, "参数错误", nil)
		return
	}

	var user model.UserInfoDBModel
	if err := db.Get().Where("openId = ?", openId).First(&user).Error; err != nil {
		util.ReturnErrorJSON(w, "用户不存在", err)
		return
	}

	var recipe model.Recipe
	if err := db.Get().First(&recipe, idStr).Error; err != nil {
		util.ReturnErrorJSON(w, "食谱不存在", err)
		return
	}

	if recipe.FamilyID != user.FamilyID {
		util.ReturnErrorJSON(w, "无权查看", nil)
		return
	}

	util.ReturnSuccessJSON(w, convertRecipeToDTO(&recipe))
}
