// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFamilyDBModel = "family"

// FamilyDBModel 家庭表
type FamilyDBModel struct {
	ID         int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:自增id" json:"id"`                   // 自增id
	Name       string    `gorm:"column:name;type:varchar(128);not null;comment:家庭名称" json:"name"`                                       // 家庭名称
	OwnerID    string    `gorm:"column:owner_id;type:varchar(128);not null;comment:创建人openId" json:"owner_id"`                          // 创建人openId
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`   // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:最后更新时间" json:"update_time"` // 最后更新时间
}

// TableName FamilyDBModel's table name
func (*FamilyDBModel) TableName() string {
	return TableNameFamilyDBModel
}
