// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMenuDBModel = "menu"

// MenuDBModel 每日菜单表
type MenuDBModel struct {
	ID         int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:自增id" json:"id"`                                       // 自增id
	FamilyID   int64     `gorm:"column:family_id;type:bigint unsigned;not null;index:idx_family_date,priority:1;comment:家庭id，关联 family 表" json:"family_id"` // 家庭id，关联 family 表
	Date       time.Time `gorm:"column:date;type:date;not null;index:idx_family_date,priority:2;comment:日期，格式 YYYY-MM-DD" json:"date"`                      // 日期，格式 YYYY-MM-DD
	MealType   int32     `gorm:"column:meal_type;type:tinyint;not null;comment:餐别：1-早餐, 2-午餐, 3-晚餐" json:"meal_type"`                                       // 餐别：1-早餐, 2-午餐, 3-晚餐
	RecipeID   int64     `gorm:"column:recipe_id;type:bigint unsigned;not null;comment:食谱id，关联 recipe 表" json:"recipe_id"`                                  // 食谱id，关联 recipe 表
	UserID     string    `gorm:"column:user_id;type:varchar(128);not null;comment:点菜人openId" json:"user_id"`                                                // 点菜人openId
	Remark     string    `gorm:"column:remark;type:varchar(255);comment:备注信息" json:"remark"`                                                                // 备注信息
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`                       // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`                       // 更新时间
}

// TableName MenuDBModel's table name
func (*MenuDBModel) TableName() string {
	return TableNameMenuDBModel
}
