// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessageDBModel = "message"

// MessageDBModel 留言表
type MessageDBModel struct {
	ID              int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:自增id" json:"id"`                          // 自增id
	FamilyID        int64     `gorm:"column:family_id;type:bigint unsigned;not null;index:idx_family_msg,priority:1;comment:家庭id" json:"family_id"` // 家庭id
	UserID          string    `gorm:"column:user_id;type:varchar(128);not null;comment:留言者openId" json:"user_id"`                                   // 留言者openId
	UserName        string    `gorm:"column:user_name;type:varchar(128);not null;comment:留言者昵称" json:"user_name"`                                   // 留言者昵称
	UserAvatar      string    `gorm:"column:user_avatar;type:varchar(512);not null;comment:留言者头像" json:"user_avatar"`                               // 留言者头像
	Content         string    `gorm:"column:content;type:text;comment:留言内容" json:"content"`                                                         // 留言内容
	ParentID        int64     `gorm:"column:parent_id;type:bigint unsigned;index:idx_parent,priority:1;comment:父留言ID" json:"parent_id"`             // 父留言ID
	ReplyToUserID   string    `gorm:"column:reply_to_user_id;type:varchar(128);comment:回复给谁" json:"reply_to_user_id"`                               // 回复给谁
	ReplyToUserName string    `gorm:"column:reply_to_user_name;type:varchar(128);comment:回复给谁的昵称" json:"reply_to_user_name"`                        // 回复给谁的昵称
	CreateTime      time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`          // 创建时间
}

// TableName MessageDBModel's table name
func (*MessageDBModel) TableName() string {
	return TableNameMessageDBModel
}
