// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRecipeDBModel = "recipe"

// RecipeDBModel 食谱表
type RecipeDBModel struct {
	ID            int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:自增id" json:"id"`                      // 自增id
	FamilyID      int64     `gorm:"column:family_id;type:bigint unsigned;not null;index:idx_family,priority:1;comment:家庭id" json:"family_id"` // 家庭id
	Name          string    `gorm:"column:name;type:varchar(128);not null;comment:食谱名称" json:"name"`                                          // 食谱名称
	Images        string    `gorm:"column:images;type:json;comment:成品照片路径列表" json:"images"`                                                   // 成品照片路径列表
	Content       string    `gorm:"column:content;type:text;comment:食谱具体内容" json:"content"`                                                   // 食谱具体内容
	CreatorID     string    `gorm:"column:creator_id;type:varchar(128);comment:创建者openId" json:"creator_id"`                                  // 创建者openId
	CreatorName   string    `gorm:"column:creator_name;type:varchar(128);comment:创建者昵称" json:"creator_name"`                                  // 创建者昵称
	CreatorAvatar string    `gorm:"column:creator_avatar;type:varchar(512);comment:创建者头像" json:"creator_avatar"`                              // 创建者头像
	SortOrder     int64     `gorm:"column:sort_order;type:bigint;not null;comment:排序字段" json:"sort_order"`                                    // 排序字段
	CreateTime    time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`      // 创建时间
	UpdateTime    time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:最后更新时间" json:"update_time"`    // 最后更新时间
}

// TableName RecipeDBModel's table name
func (*RecipeDBModel) TableName() string {
	return TableNameRecipeDBModel
}
